### ISSUE TITLE
errors and schematron message

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#195]
@ajaniak please look into the following errors. By the way, the follow schematron error message should be slighhtly corrected:

CURRENT 
"the content of resp should allowed the used to declare authorship of the digital edition itself. To declare the authorship of the text, you can use the element author. Other contribution should declared  in the lemma paragraph of the bibliography division"

SHOULD BECOME
"The content of resp allows the user to declare authorship of the digital edition itself. To declare the authorship of the text, you can use the element author. Other contributions should be declared in the free-text paragraph of the bibliography division"

<img width="1458" alt="Image" src="https://github.com/user-attachments/assets/dbc855b6-fccc-4d65-a02b-a4aea738d01b" />
<img width="546" alt="Image" src="https://github.com/user-attachments/assets/6b409e01-bcdb-4cbd-864c-ea5081534b13" />
<img width="1472" alt="Image" src="https://github.com/user-attachments/assets/51be32af-30c0-430a-9ef3-cabd4919e195" />

**Comment by ajaniak** [comment]
I just pushed the updated version of the schema for the authorship error message. However, the error regarding the filename has been corrected yesterday. After taking a look to be sure it was correctly pushed, I think you are validating with a cached schema. Relaunched Oxygen or launching manually the validation usually updates it as well.

**Comment by arlogriffiths** [comment]
thanks. strangely, both errors persist, even after manually relaunched validation and after rebooting Oxyygen...  though apparently not both errors together in a single file, and not every file is affected by one or the other.

<img width="1470" alt="Image" src="https://github.com/user-attachments/assets/99972e1e-0046-4ec0-b286-46593e1f540d" />

<img width="1475" alt="Image" src="https://github.com/user-attachments/assets/42262d56-c496-4cf5-85fd-1388366604e3" />

**Comment by ajaniak** [comment]
It keeps getting weirder ... I can't figure why we keep having those validating issues with both Oxygen and Visual Code. At least for Oxygen, it could be a version issue (mine is 23 and the current version is 27). It could explain the slowness to update the schema. But it doesn't apply for VS. And Malia has tried changing for XML Scholarly edition to XML library and it doesn't help.
