### ISSUE TITLE
edits Tattva Brata

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#239]
@ajaniak — this concerns DHARMA_CritEdTattvaBrataJava.xml.

- [x] there are numerous cases of this type: `gәriṅ<app><lem type="emn">gәriṅ</lem><rdg wit="#msA">śri</rdg><rdg wit="#msB">gri</rdg></app>` where the ocntents of `<lem>` is repeated just before the `<app>`. Can you remove all such unwanted repetitions? In this example, the desired outcome is `<app><lem type="emn">gәriṅ</lem><rdg wit="#msA">śri</rdg><rdg wit="#msB">gri</rdg></app>`
- [x] please also implements xml:id for all text blocks in this edition

cc @GunaYasa

**Comment by ajaniak** [comment]
Dear @arlogriffiths and @GunaYasa,

I have just pushed the edit of the `<app>`. I made it with a specific commit to be able to revert it easily if necessary. Please review it! 

Best, 
Axelle

**Comment by arlogriffiths** [comment]
Thanks. We usually have a blacklog of displayed htmls, lagging behind the most recent commits. Is it possible to make sure the changed version get displayed? Maybe another meaningless commit will do the trick?

**Comment by GunaYasa** [comment]
Dear Pak Arlo and Axelle.
Thanks for your help, I have checked the Tattva Brata Bali file.
The double or duplicate words still appear in the edition.
Best
Guna

Pada Jum, 23 Mei 2025 pukul 12.44 arlogriffiths ***@***.***>
menulis:

**Comment by arlogriffiths** [comment]
Thanks Axelle. A conflict arose between your and my commits on this file, I think. I have just resolved the conflict. But the xml:id numbering isn't correct, presumably due to the intervening conclift. Can you rerun the script?

**Comment by ajaniak** [comment]
I have checked the file: 
I still found some cases as 
```
taṅgal<app>
                  <lem wit="#msA">taṁgal</lem>
                  <rdg wit="#msB">tagal</rdg>
               </app> piṅ<app>
                  <lem wit="#msA">piṁ</lem>
                  <rdg wit="#msB">pi</rdg>
               </app> rva vlasiṅ<app>
                  <lem wit="#msA">vlasiṁ</lem>
                  <rdg wit="#msB">vlasi</rdg>
               </app>
```
I can't resolve them, since the string before `<app>` and the `<lem>`are not identical. If I take an automatic action, I will also delete some string you would want to keep. So you should deal with those manually.

Not sure what you mean about the `@xml:id` they seem fine to me but I have reintroduced the `@corresp` for translation. Please be careful you numbering in the edition and the translation doesn't match stricltly. I have identified some variation at the end. The coordination between the edition and translation seem to be good, but check it nonetheless to be sure.

**Comment by arlogriffiths** [comment]
Thanks Axelle. @GunaYasa will resolve those not-fully-identical double strings manually.

Yesterday, I got a validation problem due to repetition of an xml:id but now the problem is gone.

@GunaYasa (aided by @andreaacri) will pay close attention to the numbering correspondence.

I am closing this issue.

**Comment by GunaYasa** [comment]
Thanks a lot @Arlo Griffiths ***@***.***> and Axelle for your
help n advice.

Best,
Guna

Pada Sab, 24 Mei 2025, 02.01, arlogriffiths ***@***.***>
menulis:
